var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var passportLocalMongoose = require('passport-local-mongoose');

var Pretrip = new Schema({
	creatorID: String,
	pretripNum: Number,
	vehicleLicencePlate: String,
	fleet: String,
	backUpLighs: Boolean,
	brakeLights: Boolean,
	emergencyFlashers: Boolean,
	headLights_high_low : Boolean,
	interiorLights : Boolean,
	sideMarkers : Boolean,
	turnSignals : Boolean,
	licensePlate : Boolean,
	oil : Boolean,
	visualPressureCheck : Boolean,
	preAndPostTripBodyInspection : Boolean,
	windshieldVisibility : Boolean,
	mirrors : Boolean,
	steering : Boolean,
	horn : Boolean,
	fuelLevel : Boolean,
	wipers: Boolean,
	seatBelts_lifts_straps: Boolean,
	oil_levels: String,
	coolant_levels: String,
	transmissionFluids_levels: String,
	powerSteering_levels: String,
	brakeFluid_levels: String,
	wiperFluid_levels: String,
	belts: String,
	leaks: String,
	battery: String,
	wiring: String,
	hoses: String,
	clamps: String,
	measurePressure: String,
	lugNuts: String,
	treads: String,
	rims: String,
	spare: String,
	flares: String,
	fireExtinguisher: String,
	jack_wheelWrench: String,
	seatBeltClutter: String,
	boosterCables: String,
	vehicleDocument_insurance: String,
	frontImage: String,
	leftImage: String,
	rightImage: String,
	backImage: String,
	fixed: Boolean,
	notes: String,
	dateArchieved: { type : Date, default: new Date() }
});

module.exports = mongoose.model('pretrip', Pretrip);